# Generated by Django 3.0.4 on 2020-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('s', 'sale'), ('R', 'rent')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beds_number', models.PositiveIntegerField()),
                ('kitchen_number', models.PositiveIntegerField()),
                ('leavingroom_number', models.PositiveIntegerField()),
                ('baths_number', models.PositiveIntegerField()),
                ('garages_number', models.PositiveIntegerField()),
            ],
        ),
    ]
