# Generated by Django 3.0.4 on 2020-04-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200403_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('S', 'sale'), ('R', 'rent'), ('B', 'buy')], max_length=10),
        ),
    ]
